from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from ..models import GeneratorConfig
from ..registry import FamilyRegistry
from .common import build_entry, html_active_content_sample, write_artifact, write_recipe


HTML_EXTENSION = "html"


def run_mitra(
    mitra_path: Path,
    seed_a: Path,
    seed_b: Path,
    out_dir: Path,
    timeout_seconds: int = 30,
) -> tuple[list[Path], dict[str, object]]:
    before = {path.relative_to(out_dir) for path in out_dir.rglob("*") if path.is_file()}
    command = ["python3", str(mitra_path.resolve()), "-f", str(seed_a.resolve()), str(seed_b.resolve())]
    completed = subprocess.run(
        command,
        cwd=out_dir,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
    )
    after = {path.relative_to(out_dir) for path in out_dir.rglob("*") if path.is_file()}
    created = sorted(
        out_dir / relative_path
        for relative_path in after - before
        if (out_dir / relative_path).is_file()
    )
    provenance = {
        "source": "mitra",
        "command": command,
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
        "seed_a": seed_a.name,
        "seed_b": seed_b.name,
        "force_second_as_blob": True,
        }
    return created, provenance


def polyglot_labels(config: GeneratorConfig) -> list[str]:
    labels = list(config.selected_extensions)
    if HTML_EXTENSION not in labels:
        labels.append(HTML_EXTENSION)
    return labels


def seed_path_for_label(temp_dir: Path, label: str, registry: FamilyRegistry) -> Path:
    if label == HTML_EXTENSION:
        seed_path = temp_dir / f"seed-{label}.html"
        seed_path.write_text(html_active_content_sample(), encoding="utf-8")
        return seed_path
    family_id = registry.family_for_extension(label)
    plugin = registry.get_plugin(family_id)
    seed_path = temp_dir / f"seed-{label}.{label}"
    seed_path.write_bytes(plugin.generate_valid(label).data)
    return seed_path


def pair_labels(config: GeneratorConfig) -> list[tuple[str, str]]:
    labels = polyglot_labels(config)
    return [(left, right) for left in config.selected_extensions for right in labels if right != left]


def infer_mitra_feature(filename: str) -> str:
    upper_name = filename.upper()
    if upper_name.startswith("Z("):
        return "zipper"
    if upper_name.startswith("P("):
        return "parasite"
    if upper_name.startswith("C("):
        return "cavity"
    if upper_name.startswith("S("):
        return "stack"
    if upper_name.startswith("O("):
        return "overlap-near-polyglot"
    return "polyglot"


def describe_mitra_feature(feature: str) -> str:
    descriptions = {
        "zipper": "Zipper layout where both formats interleave and switch ownership at several offsets.",
        "parasite": "Parasite layout where one format is embedded inside a tolerated comment-like or payload-carrying area of the other.",
        "cavity": "Cavity layout where one format is placed into unused or blank space tolerated by the other format.",
        "stack": "Stack layout where one format is appended after the other and one or both parsers tolerate trailing data.",
        "overlap-near-polyglot": "Near-polyglot layout with overlapping bytes shared by both formats.",
        "polyglot": "Polyglot layout generated by Mitra where multiple parsers may interpret the same bytes differently.",
    }
    return descriptions[feature]


def cleanup_empty_pair_dir(pair_dir: Path) -> None:
    contents = sorted(path.name for path in pair_dir.iterdir())
    if contents == ["mitra.log"]:
        (pair_dir / "mitra.log").unlink()
        pair_dir.rmdir()


def generate(config: GeneratorConfig, registry: FamilyRegistry) -> list:
    write_recipe(
        config,
        "polyglots/manual-html-seed.html",
        html_active_content_sample(),
    )
    write_recipe(
        config,
        "polyglots/html-manual-test-notes.md",
        "\n".join(
            [
                "# HTML polyglot helpers",
                "",
                "This directory includes an HTML seed that can be used manually and, when Mitra is configured, as a forced blob payload for any host format tested by this generator.",
                "Mitra has no dedicated HTML parser in its main parser set, so HTML is always passed as file 2 with `-f` and handled through Mitra's generic blob path.",
                "This generator now also forces non-HTML file2 payloads through the same path so every ordered pair follows one consistent Mitra invocation model.",
                "",
                "Use `manual-html-seed.html` to probe cases such as:",
                "- a stored upload later served inline as HTML",
                "- an uploaded file embedded into an `<iframe>` or preview widget",
                "- a disguised active-content file whose extension suggests an image or document",
                "- downstream transformations or wrappers that preserve executable markup",
                "",
                "When Mitra is enabled, each host extension is paired against every other selected extension plus HTML, always with `-f`.",
            ]
        )
        + "\n",
    )
    if config.mitra_path is None:
        return []

    out_dir = config.out_dir / "polyglots"
    out_dir.mkdir(parents=True, exist_ok=True)
    entries = []

    for left, right in pair_labels(config):
        pair_dir = out_dir / f"{left}-{right}"
        pair_dir.mkdir(parents=True, exist_ok=True)
        should_cleanup_pair_dir = False

        with tempfile.TemporaryDirectory(dir=pair_dir) as temp_dir_name:
            temp_dir = Path(temp_dir_name)
            left_seed = seed_path_for_label(temp_dir, left, registry)
            right_seed = seed_path_for_label(temp_dir, right, registry)

            try:
                created, provenance = run_mitra(config.mitra_path, left_seed, right_seed, temp_dir)
            except Exception:
                continue

            log_path = pair_dir / "mitra.log"
            log_path.write_text(
                f"command: {provenance['command']}\n"
                f"returncode: {provenance['returncode']}\n"
                f"stdout:\n{provenance['stdout']}\n"
                f"stderr:\n{provenance['stderr']}\n",
                encoding="utf-8",
            )

            for index, source_path in enumerate(created, start=1):
                source_data = source_path.read_bytes()
                mitra_name = source_path.name
                feature = infer_mitra_feature(mitra_name)
                relative_path = f"polyglots/{left}-{right}/{mitra_name}"
                write_artifact(config, relative_path, source_data)
                logical_extension = Path(mitra_name).suffix.lstrip(".") or "bin"
                entries.append(
                    build_entry(
                        config=config,
                        category="polyglots",
                        relative_path=relative_path,
                        logical_extension=logical_extension,
                        generated_content_family=f"{left}-{right}",
                        expected_magic=source_data[: min(8, len(source_data))],
                        expected_mime="application/octet-stream",
                        mismatch=True,
                        risk_level="medium",
                        generator="polyglots.generate",
                        description=(
                            f"Mitra-generated {feature} polyglot from .{left} host bytes and .{right} payload bytes. "
                            f"File2 is passed to Mitra with `-f` as a forced blob payload. "
                            f"{describe_mitra_feature(feature)}"
                        ),
                        expected_behavior=(
                            "Different validators, MIME sniffers, and downstream parsers may disagree about which file type this forced-blob polyglot represents."
                        ),
                        data=source_data,
                        provenance={
                            **dict(provenance),
                            "mitra_feature": feature,
                            "mitra_filename": mitra_name,
                            "host_extension": left,
                            "payload_extension": right,
                        },
                    )
                )

            feature_lines = []
            for source_path in created:
                mitra_name = source_path.name
                feature = infer_mitra_feature(mitra_name)
                feature_lines.append(
                    f"{mitra_name}: host=.{left}; payload=.{right}; feature={feature}; forced_blob=true; {describe_mitra_feature(feature)}"
                )
            if feature_lines:
                (pair_dir / "mitra-features.log").write_text("\n".join(feature_lines) + "\n", encoding="utf-8")
            elif not config.debug:
                should_cleanup_pair_dir = True

        if should_cleanup_pair_dir:
            cleanup_empty_pair_dir(pair_dir)

    return entries
